sudo: required
services:
  - docker

before_install:
  - docker build -t ortizjd/covid-19-board:latest -f Dockerfile .

script:
  - docker run -e CI=true ortizjd/covid-19-board:latest npm run test

after_success:
  - docker build -t ortizjd/covid-19-board:latest .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take image and push them to docker hub
  - docker tag ortizjd/covid-19-board:latest 

  - docker push ortizjd/covid-19-board:latest

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "covid-19-board"
  env: "Covid19Board-env"
  bucket_name: "elasticbeanstalk-us-east-1-263638668305"
  bucket_path: "covid-19-board"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
